typedef:sig_atomic_t
typedef:sigset_t
typedef:pid_t
typedef:sigevent

function:bsd_signal
function:kill
function:killpg
function:pthread_kill
function:pthread_sigmask
function:raise
function:sigaction
function:sigaddset
function:sigaltstack
function:sigdelset
function:sigemptyset
function:sigfillset
function:sighold
function:sigignore
function:siginterrupt
function:sigismember
function:signal
function:sigpause
function:sigpending
function:sigprocmask
function:sigqueue
function:sigrelse
function:sigset
function:sigsuspend
function:sigtimedwait
function:sigwait
function:sigwaitinfo
