typedef:FILE
typedef:fpos_t
typedef:va_list
typedef:size_t;

function:clearerr
function:ctermid
function:fclose
function:fdopen
function:feof
function:ferror
function:fflush
function:fgetc
function:fgetpos
function:fgets
function:fileno
function:flockfile
function:fopen
function:fprintf
function:fputc
function:fputs
function:fread
function:freopen
function:fscanf
function:fseek
function:fseeko
function:fsetpos
function:ftell
function:ftello
function:ftrylockfile
function:funlockfile
function:fwrite
function:getc
function:getchar
function:getc_unlocked
function:getchar_unlocked
function:gets
function:pclose
function:perror
function:popen
function:printf
function:putc
function:putchar
function:putc_unlocked
function:putchar_unlocked
function:puts
function:remove
function:rename
function:rewind
function:scanf
function:setbuf
function:setvbuf
function:snprintf
function:sprintf
function:sscanf
function:tempnam
function:tmpfile
function:tmpnam
function:ungetc
function:vfprintf
function:vfscanf
function:vprintf
function:vscanf
function:vsnprintf
function:vsprintf
function:vsscanf
