typedef:div_t
typedef:ldiv_t
typedef:lldiv_t
typedef:size_t
typedef:wchar_t

function:_Exit
function:a64l
function:abort
function:abs
function:atexit
function:atof
function:atoi
function:atol
function:atoll
function:bsearch
function:calloc
function:div
function:drand48
function:ecvt
function:erand48
function:exit
function:fcvt
function:free
function:gcvt
function:getenv
function:getsubopt
function:grantpt
function:initstate
function:jrand48
function:l64a
function:labs
function:lcong48
function:ldiv
function:llabs
function:lldiv
function:lrand48
function:malloc
function:mblen
function:mbstowcs
function:mbtowc
function:mktemp
function:mkstemp
function:mrand48
function:nrand48
function:posix_memalign
function:posix_openpt
function:ptsname
function:putenv
function:qsort
function:rand
function:rand_r
function:random
function:realloc
function:realpath
function:seed48
function:setenv
function:setkey
function:setstate
function:srand
function:srand48
function:srandom
function:strtod
function:strtof
function:strtol
function:strtold
function:strtoll
function:strtoul
function:strtoull
function:system
function:unlockpt
function:unsetenv
function:wcstombs
function:wctomb
