typedef:clock_t
typedef:size_t
typedef:time_t
typedef:clockid_t
typedef:timer_t

function:asctime
function:asctime_r
function:clock
function:clock_getcpuclockid
function:clock_getres
function:clock_gettime
function:clock_nanosleep
function:clock_settime
function:ctime
function:ctime_r
function:difftime
function:getdate
function:gmtime
function:gmtime_r
function:localtime
function:localtime_r
function:mktime
function:nanosleep
function:strftime
function:strptime
function:time
function:timer_create
function:timer_delete
function:timer_gettime
function:timer_getoverrun
function:timer_settime
function:tzset
