typedef:wchar_t
typedef:wint_t
typedef:wctype_t
typedef:mbstate_t
typedef:FILE
typedef:size_t
typedef:va_list

function:btowc
function:fgetwc
function:fgetws
function:fputwc
function:fputws
function:fwide
function:fwprintf
function:fwscanf
function:getwc
function:getwchar
function:iswalnum
function:iswalpha
function:iswcntrl
function:iswctype
function:iswdigit
function:iswgraph
function:iswlower
function:iswprint
function:iswpunct
function:iswspace
function:iswupper
function:iswxdigit
function:mbrlen
function:mbrtowc
function:mbsinit
function:mbsrtowcs
function:putwc
function:putwchar
function:swprintf
function:swscanf
function:towlower
function:towupper
function:ungetwc
function:vfwprintf
function:vfwscanf
function:vwprintf
function:vswprintf
function:vswscanf
function:vwscanf
function:wcrtomb
function:wcscat
function:wcschr
function:wcscmp
function:wcscoll
function:wcscpy
function:wcscspn
function:wcsftime
function:wcslen
function:wcsncat
function:wcsncmp
function:wcsncpy
function:wcspbrk
function:wcsrchr
function:wcsrtombs
function:wcsspn
function:wcsstr
function:wcstod
function:wcstof
function:wcstok
function:wcstol
function:wcstold
function:wcstoll
function:wcstoul
function:wcstoull
function:wcswcs
function:wcswidth
function:wcsxfrm
function:wctob
function:wctype
function:wcwidth
function:wmemchr
function:wmemcmp
function:wmemcpy
function:wmemmove
function:wmemset
function:wprintf
function:wscanf

