function:cabs
function:cabsf
function:cabsl
function:cacos
function:cacosf
function:cacosh
function:cacoshf
function:cacoshl
function:cacosl
function:carg
function:cargf
function:cargl
function:casin
function:casinf
function:casinh
function:casinhf
function:casinhl
function:casinl
function:catan
function:catanf
function:catanh
function:catanhf
function:catanhl
function:catanl
function:ccos
function:ccosf
function:ccosh
function:ccoshf
function:ccoshl
function:ccosl
function:cexp
function:cexpf
function:cexpl
function:cimag
function:cimagf
function:cimagl
function:clog
function:clogf
function:clogl
function:conj
function:conjf
function:conjl
function:cpow
function:cpowf
function:cpowl
function:cproj
function:cprojf
function:cprojl
function:creal
function:crealf
function:creall
function:csin
function:csinf
function:csinh
function:csinhf
function:csinhl
function:csinl
function:csqrt
function:csqrtf
function:csqrtl
function:ctan
function:ctanf
function:ctanh
function:ctanhf
function:ctanhl
function:ctanl

