function:isalnum
function:isalpha
function:isascii
function:isblank
function:iscntrl
function:isdigit
function:isgraph
function:islower
function:isprint
function:ispunct
function:isspace
function:isupper
function:isxdigit
function:toascii
function:tolower
function:toupper
function:_toupper
function:_tolower
