typedef:float_t
typedef:double_t

function:fpclassify
function:isfinite
function:isinf
function:isnan
function:isnormal
function:signbit
function:isgreater
function:isgreaterequal
function:isless
function:islessequal
function:islessgreater
function:isunordered

function:acos
function:acosf
function:acosh
function:acoshf
function:acoshl
function:acosl
function:asin
function:asinf
function:asinh
function:asinhf
function:asinhl
function:asinl
function:atan
function:atan2
function:atan2f
function:atan2l
function:atanf
function:atanh
function:atanhf
function:atanhl
function:atanl
function:cbrt
function:cbrtf
function:cbrtl
function:ceil
function:ceilf
function:ceill
function:copysign
function:copysignf
function:copysignl
function:cos
function:cosf
function:cosh
function:coshf
function:coshl
function:cosl
function:erf
function:erfc
function:erfcf
function:erfcl
function:erff
function:erfl
function:exp
function:exp2
function:exp2f
function:exp2l
function:expf
function:expl
function:expm1
function:expm1f
function:expm1l
function:fabs
function:fabsf
function:fabsl
function:fdim
function:fdimf
function:fdiml
function:floor
function:floorf
function:floorl
function:fma
function:fmaf
function:fmal
function:fmax
function:fmaxf
function:fmaxl
function:fmin
function:fminf
function:fminl
function:fmod
function:fmodf
function:fmodl
function:frexp
function:frexpf
function:frexpl
function:hypot
function:hypotf
function:hypotl
function:ilogb
function:ilogbf
function:ilogbl
function:j0
function:j1
function:jn
function:ldexp
function:ldexpf
function:ldexpl
function:lgamma
function:lgammaf
function:lgammal
function:llrint
function:llrintf
function:llrintl
function:llround
function:llroundf
function:llroundl
function:log
function:log10
function:log10f
function:log10l
function:log1p
function:log1pf
function:log1pl
function:log2
function:log2f
function:log2l
function:logb
function:logbf
function:logbl
function:logf
function:logl
function:lrint
function:lrintf
function:lrintl
function:lround
function:lroundf
function:lroundl
function:modf
function:modff
function:modfl
function:nan
function:nanf
function:nanl
function:nearbyint
function:nearbyintf
function:nearbyintl
function:nextafter
function:nextafterf
function:nextafterl
function:nexttoward
function:nexttowardf
function:nexttowardl
function:pow
function:powf
function:powl
function:remainder
function:remainderf
function:remainderl
function:remquo
function:remquof
function:remquol
function:rint
function:rintf
function:rintl
function:round
function:roundf
function:roundl
function:scalb
function:scalbln
function:scalblnf
function:scalblnl
function:scalbn
function:scalbnf
function:scalbnl
function:sin
function:sinf
function:sinh
function:sinhf
function:sinhl
function:sinl
function:sqrt
function:sqrtf
function:sqrtl
function:tan
function:tanf
function:tanh
function:tanhf
function:tanhl
function:tanl
function:tgamma
function:tgammaf
function:tgammal
function:trunc
function:truncf
function:truncl
function:y0
function:y1
function:yn
