typedef:size_t

function:memccpy
function:memchr
function:memcmp
function:memcpy
function:memmove
function:memset
function:strcat
function:strchr
function:strcmp
function:strcoll
function:strcpy
function:strcspn
function:strdup
function:strerror
function:strerror_r
function:strlen
function:strncat
function:strncmp
function:strncpy
function:strpbrk
function:strrchr
function:strspn
function:strstr
function:strtok
function:strtok_r
function:strxfrm
